Домашка по созданию разметки по макету Главной страницы проекта "Седона"
htmlacademy-htmlcss/1853053-sedona-33 pull request #2
Opened 2022-01-23 13:53 UTC by ARURIO

2022-01-23 19:22 UTC, andreysgra requested changes
Задание называется "Разметка главной страницы" и значит нужно разметить только главную страницу. По заданию нужно делать не меньше и не больше сказанного. Если для внутренней страницы существует отдельное задание, то работу с ней нужно вести в том задании. Не нужно всё сваливать в одну кучу.

Во-первых, это усложняет мою работу и увеличивает время проверки, а во-вторых, это усложняет работу и вам - приходится тратить больше времени на работу с заданием. Кроме того, на обеих страницах есть однотипные блоки, например шапка и подвал. Допустив ошибку на главной странице вы допускаете точно такую же и на другой.

Я проверял только главную страницу. Над внутренней будем работать, когда все мои замечания по главной будут устранены. Будет лучше, если вы на время уберёте из проекта файл **catalog.html**. Когда я приму задание по главной странице, то файл вернёте в проект и отправите на проверку следующее задание.

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +          <a class="navigation-link" href="#">Главная</a>
В задании написано:

> Если страницы нет в макете, то ссылка на неё должна быть следующего вида — `<a href="#"></a>`

Страница "Главная" в макете есть, значит на неё должна быть реальная ссылка.

Есть мнение, что страница не должна ссылаться на себя. В таком случае, чтобы ссылка была нерабочей, нужно убрать у неё атрибут `href`.

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +        заслуживающий большего!</p>
Текст внутри параграфа можно обернуть тегом `b`. Этот тег используется для привлечения внимания к тексту. Будет выглядеть так:
```
<p><b>Седона — небольшой городок в Аризоне, заслуживающий большего!</b></p>
```

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +      <ul class="features-list">
Да, перечисление причин - это список, и его даже лучше сделать нумерованным, то есть использовать вместо `ul`, тег `ol`.

Но распределение на элементы списка у вас не совсем верное. Перечисленных причин пять, следовательно и элементов списка `li` тоже должно быть пять:
![image](https://user-images.githubusercontent.com/17790771/150693661-bca4d3dc-482f-4989-b9c0-50f1049c3e1b.png)

Первый пункт списка кроме собственного контента будет иметь вложенный список `ul` состоящий из трёх элементов:
![image](https://user-images.githubusercontent.com/17790771/150693712-eb4a37fc-09d1-442a-be68-e4030f5397f7.png)

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +        </li>
Как писал выше это отдельный, вложенный в первый элемент, список.

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +          <h3 class="features-title-icon">Сувениры</h3>
Так как список вложенный, то чтобы соблюсти иерархию заголовков, нужно использовать здесь `h4` вместо `h3`.

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +      <h3 class="search-hotel-title">Заинтересовались?</h3>
У вас выше есть уже срытый заголовок описывающий эту секцию. Зачем здесь ещё один? Да и кроме того данный текст мало подходит на роль заголовка. Здесь стоит использовать параграф (можно также ещё текст обернуть тегом `b`).

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +      <a class="button-search-hotel" href="catalog.html">ПОИСК ГОСТИНИЦЫ В седоне</a>
Пишите текст в общепринятом смысле - предложение начинается с заглавной буквы, остальные - строчные.

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +            <span>Подписаться</span>
`<span>` здесь совершенно не нужен. Это просто лишний тег в разметке (критерий [HTML-06](https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-06)).

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +        </a>
В требованиях (соответствующий фрейм в макете) есть такая информация:
![image](https://user-images.githubusercontent.com/17790771/150694139-da0e66a4-ddbe-427d-94f6-f1e3a2108a7e.png)

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +        <p class="phone-number">+7 (812) 812-12-12</p>
Это ссылка для телефона в соответствующем формате (смотрите в описании критерия [HTML-03](https://up.htmlacademy.ru/htmlcss/33/criteries#HTML-03)).

2022-01-23 19:22 UTC, andreysgra commented on index.html
> +      <a class="logo_htmlacademy">
В требованиях написано:
![image](https://user-images.githubusercontent.com/17790771/150694227-a7daf38d-d0d3-4227-8e5d-db6e9f2a4050.png)

2022-01-24 06:13 UTC, ARURIO commented on index.html
> +          <a class="navigation-link" href="#">Главная</a>
Исправил

2022-01-24 06:14 UTC, ARURIO commented on index.html
> +          <a class="navigation-link" href="#">Главная</a>
Исправил на index.html

2022-01-24 06:14 UTC, ARURIO commented on index.html
> +          <a class="navigation-link" href="#">Главная</a>
Исправил на index.html

2022-01-24 06:15 UTC, ARURIO commented on index.html
> +          <a class="navigation-link" href="#">Главная</a>
Исправил на index.html

2022-01-24 06:18 UTC, ARURIO commented on index.html
> +        заслуживающий большего!</p>
Поменял

2022-01-24 06:33 UTC, ARURIO commented on index.html
> +      <ul class="features-list">
Изменил ненумерованный на нумерованный, добавил в 1 пункт дополнительный ненумерованный список

2022-01-24 06:35 UTC, ARURIO commented on index.html
> +        </li>
Сделал дополнительный список

2022-01-24 06:36 UTC, ARURIO commented on index.html
> +          <h3 class="features-title-icon">Сувениры</h3>
Добавил заголовки 4 уровня

2022-01-24 06:48 UTC, ARURIO commented on index.html
> +            <span>Подписаться</span>
Убрал

2022-01-24 06:57 UTC, ARURIO commented on index.html
> +        </a>
Добавил реальные ссылки

2022-01-24 07:02 UTC, ARURIO commented on index.html
> +      <a class="logo_htmlacademy">
Исправил

2022-01-24 07:17 UTC, ARURIO commented on index.html
> +        <p class="phone-number">+7 (812) 812-12-12</p>
Сделал правильную ссылку на телефон

2022-01-24 09:56 UTC, merged